version: "3.9"
services:
  grafana:
    container_name: grafana
    restart: always
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_conf:/usr/share/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin

volumes:
  grafana_data:
  grafana_conf:

networks:
  default:
    external:
      name: monitoring