version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresqlpassword
    restart: always
    volumes:
      - pgdatavol:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "8080:3000"
    depends_on:
      - db
volumes:
  pgdatavol: