apiVersion: v1
kind: Service
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-001
    app.kubernetes.io/version: "5.5"
    app.kubernetes.io/component: server
spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-001
    app.kubernetes.io/version: "5.5"
    app.kubernetes.io/component: server
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-001
    app.kubernetes.io/version: "5.5"
    app.kubernetes.io/component: server
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app01
  labels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/instance: wordpress-001
    app.kubernetes.io/version: "5.5"
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wordpress
      app.kubernetes.io/instance: wordpress-001
      app.kubernetes.io/version: "5.5"
      app.kubernetes.io/component: server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordpress
        app.kubernetes.io/instance: wordpress-001
        app.kubernetes.io/version: "5.5"
        app.kubernetes.io/component: server
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - wordpress
            topologyKey: "kubernetes.io/hostname"
#      imagePullSecrets:
#        - name: private-registry
      containers:
      - image: wordpress:5.5
        imagePullPolicy: Always
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 256Mi
            cpu: "0.25"
        name: wordpress
        env:
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: wordpress_db_user
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: wordpress_db_host
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: wordpress_db_name
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
        - name: wordpress
          mountPath: /var/www/html
      volumes:
      - name: wordpress
        persistentVolumeClaim:
          claimName: frontend-app01