apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: www-kustomize-com
namePrefix: www-kustomize-com-
nameSuffix: "-001"  
secretGenerator:
- name: kustomize-password
  literals:
  - password=password
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/part-of: wordpress
  app.kubernetes.io/managed-by: github
  app.kubernetes.io/created-by: controller-manager
resources:
#  - private-registry
  - configmap.yaml
  - cluster-issuer.yaml
  - ingress-tls.yaml
  - deployment-frontend-app01.yaml
  - deployment-backend-db01.yaml
transformers:
  - transformer-label.yaml
  - transformer-annotations.yaml
configurations:
  - name-preffix-suffix.yaml