apiVersion: v1
kind: Service
metadata:
  name: backend-db01
spec:
  selector:
    app: backend-db01
    tier: backend
  type: NodePort
  ports:
    - port: 33306
      targetPort: 3306
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-db01
  labels:
    app: redmine
    tier: backend
spec:
  resources:
    requests:
      storage: 3Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-db01
  labels:
    app: redmine
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redmine
      tier: backend
  template:
    metadata:
      labels:
        app: redmine
        tier: backend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - backend
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: backend-db01
        image: backend-image-01
        imagePullPolicy: Always
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password      
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: mariadb_database
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: kustomize-password
              key: password
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              name: template-config
              key: mariadb_user_rm  
        resources:
          limits:
            memory: 512Mi
            cpu: "0.5"
          requests:
            memory: 512Mi
            cpu: "0.25"
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: backend-db01
          mountPath: /var/lib/mysql
      imagePullSecrets:
        - name: gitlab-registry
      volumes:
      - name: backend-db01
        persistentVolumeClaim:
          claimName: backend-db01
      