apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: redmine   # kustmize
namePrefix: redmine-  # kustmize
nameSuffix: "-001"              # kustmize
secretGenerator:
- name: kustomize-password
  literals:
  - password=password
generatorOptions:
  disableNameSuffixHash: true
commonLabels:
  app.kubernetes.io/part-of: redmine
  app.kubernetes.io/managed-by: github
  app.kubernetes.io/created-by: controller-manager
resources:
  - configmap.yaml
  - cluster-issuer.yaml
  - ingress-tls.yaml
  - deployment-frontend-app01.yaml
  - deployment-backend-db01.yaml
transformers:
  - transformer-label.yaml
  - transformer-annotations.yaml
configurations:
  - name-preffix-suffix.yaml
images:
  - name: frontend-image-01
    newName: redmine
    newTag: "4.2"
  - name: backend-image-01
    newName: mariadb
    newTag: "10.5"
patchesStrategicMerge:
- |-
  apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    name: ingress-tls
  spec:
    tls:
    - hosts:
        - www.example.com
    rules:
    - host: www.example.com
- |-
  apiVersion: cert-manager.io/v1
  kind: ClusterIssuer
  metadata:
    name: cluster-issuer
  spec:
    acme:
      email: example@example.com
      solvers:
      - http01:
          ingress:
            class: nginx