- name: sshd_config
  hosts: node
  become: yes
  gather_facts: no
  tasks:
    - name: configer
      shell:
        cmd: |
          cat << EOF > /etc/ssh/sshd_config
          Subsystem sftp  /usr/lib/openssh/sftp-server
          SyslogFacility AUTHPRIV 
          LogLevel VERBOSE
          Protocol 2
          UsePAM no
          ChallengeResponseAuthentication no
          Port 22
          #PermitRootLogin no #rootログイン無効
          PubkeyAuthentication yes 
          AuthorizedKeysFile %h/.ssh/authorized_keys
          #AllowUsers UserName
          PermitEmptyPasswords no
          EOF