- name: Kubernetes configuer 
  hosts: node
  become: yes
  gather_facts: no
  tasks:
    - name: Kubernetes configuer
      shell:
        cmd: |
          microk8s enable helm3
          snap alias microk8s.helm3 helm