- name: config
  hosts: node
  become: yes
  gather_facts: no
  tasks:
    - name: microk8s configuer
      shell:
        cmd: |
          echo "--allow-privileged=true" >> /var/snap/microk8s/current/args/kubelet ; systemctl restart snap.microk8s.daemon-kubelet
          