- name: CMDLINE UPDATE
  hosts: node
  become: yes
  gather_facts: no
  tasks:
  - name: CMDLINE UPDATE
    shell:
      cmd: |
        cat <<EOF > /boot/firmware/cmdline.txt
        net.ifnames=0 dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=LABEL=writable rootfstype=ext4 elevator=deadline rootwait fixrtc cgroup_enable=memory cgroup_memory=1 usb-storage.quirks=152d:0578:u
        EOF
  - name: REBOOT
    reboot: