apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cluster-issuer
spec:
  acme:
    email: patchesstrategicmerge
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: cluster-issuer-secret
    solvers:
    - http01:
        ingress:
          class: patchesstrategicmerge # MicroK8s = public , K8s = nginx