apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kustomize
  name: template-config
data:
  WP_HOME: http://www.domain.com
  WP_SITEURL: http://www.domain.com
  TABLE_PREFIX: wp_
#  WP_CONTENT_DIR: /var/www/domain.com/wp-content
  FS_METHOD: direct
  WP_DEBUG: "false"
  WP_DEBUG_LOG: "false"
  WP_DEBUG_DISPLAY: "false"
  WP_POST_REVISIONS: "3"
  DB_CHARSET: utf8mb4
  DB_COLLATE: ""
  DB_NAME: wordpress
  DB_USER: root
  WORDPRESS_DB_HOST: kustomize-backend-001:33300