apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-domain-com
spec:
  rules:
  - host: www.domain.work
    http:
      paths:
      - backend:
          serviceName: frontend
          servicePort: 80