---
- name: add repository glusterfs server
  hosts: node
  become: yes
  gather_facts: no
  tasks:
    - name: Add glusterfs repository from PPA and install its signing key on Ubuntu target
      ansible.builtin.apt_repository:
        repo: ppa:gluster/glusterfs-9
- name: deploy httpd server
  hosts: node
  become: yes
  gather_facts: no
  tasks:
    - name: install httpd
      apt:
        name: apache2
        state: latest
        update_cache: yes
    - name: start & enabled httpd
      service:
        name: apache2
        state: started
        enabled: yes
- name: deploy glusterfs server
  hosts: node
  become: yes
  gather_facts: no
  tasks:
    - name: gluster install
      apt:
        name: glusterfs-server
        state: latest
        update_cache: yes
    - name: start & enabled glusterfs server
      service:
        name: glusterd
        state: started
        enabled: yes
- name: deploy docker 
  hosts: node
  become: yes
  gather_facts: no
  tasks:
      - name: docker install
        apt: 
          name: docker
          state: latest
          update_cache: yes
####### docker in docker の設定は行っていないため起動させない
#      - name: start & enabled docker
#        service:
#          name: docker
#          state: started
#          enabled: yes
- name: deploy docker-compose
  hosts: node
  become: yes
  gather_facts: no
  tasks:
      - name: docker-compose install
        apt:
          name: docker-compose
          state: latest
          update_cache: yes
####### docker in docker の設定は行っていないため起動させない
#      - name: start & enabled docker-compose
#        service:
#            name: docker-compose
#            state: started
#            enabled: yes

