- name: Kubernetes configuer 
  hosts: node5
  become: yes
  gather_facts: no
  tasks:
    - name: Kubernetes configuer
      shell:
        cmd: |
          kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml